Erros de Execução durante à utilização do PDV após sincronização de Espécies
Após simular o Bug #17477 das espécies, foi sincronizado e atualizado apenas a espécie DINHEIRO para Dinheiro:

Na execução do PDV, foram encontrados os seguintes erros:

* *Erro 1:*
> Ao tentar abrir o caixa e adicionar um valor de suprimento de 50,00 deu erro de NullPointer, relacionado à data de abertura, após isso tentei abrir o caixa novamente com o mesmo valor e entrou novamente;

* *Erro 2:*
> Ao tentar adicionar um item para vender deu uma mensagem de "lazyload failed", foi verificado que houve um erro no Modelo ao tentar dar load em "itensModelo", ao tentar inserir novamente o item ocorreu tudo normalmente;

* Após esses procedimentos, durante a sincronização notou-se que houve uma lentidão ao conectar ao painel para sincronizar os dados. 
